number = 2;
counter = 50;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);
counter--;
result = counter*number;
console.log(result);