number = 5;
counter = 1;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
counter++;
result = counter*number;
console.log(counter,'*',number,'=',result);
